

import numpy as np
from PIL import Image
from torchvision import transforms
from torch import optim
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.datasets as datasets
from torch.utils.data import DataLoader
import torchvision.transforms as transforms
from torch.utils.tensorboard import SummaryWriter
import deeplake as dl
from WGAN_gradient_plenty import weight_penality
from initialize_weights import initialize_weights
from Generator import Generator
from Critics import Critic

import time
# hyperparameters
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
ds = dl.load("hub://activeloop/places205")
# Hyperparameters
learning_rate = 1e-4
batch_size = 64
img_size = 64
channels_image = 3
latent_vector_dim = 100
total_epochs = 50
features_discriminator = 64
features_generator = 64
critic_iterations = 5
lambda_gradient_penalty = 10

max_batches = 5000 // batch_size

# Function to adjust channels in images


def adjust_image_channels(image_tensor):
    """
    Adjusts the channels of an image tensor.
    If the image is grayscale (1 channel), it converts it to RGB (3 channels).
    """
    if image_tensor.shape[0] == 1:
        image_tensor = image_tensor.repeat(3, 1, 1)  # Convert grayscale to RGB
    return image_tensor


# Image transformation pipeline
image_transforms = transforms.Compose([
    transforms.ToTensor(),  # Convert to Tensor
    transforms.Lambda(adjust_image_channels),  # Adjust channels if necessary
    transforms.Resize((img_size, img_size)),  # Resize the image
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])  # Normalize
])

# Data loader
data_loader = ds.pytorch(batch_size=batch_size, num_workers=0,
                         transform={'images': image_transforms, 'labels': None}, shuffle=True)

# Initialize models
generator = Generator(latent_vector_dim, channels_image,
                      features_generator).to(device)
discriminator = Critic(channels_image, features_discriminator).to(device)
initialize_weights(generator)
initialize_weights(discriminator)

# Optimizers
optimizer_generator = optim.Adam(
    generator.parameters(), lr=learning_rate, betas=(0.0, 0.9))
optimizer_discriminator = optim.Adam(discriminator.parameters(),
                                     lr=learning_rate, betas=(0.0, 0.9))

# Fixed noise for generating images
fixed_noise_sample = torch.randn(32, latent_vector_dim, 1, 1).to(device)

# TensorBoard Writers
writer_real_images = SummaryWriter(f"logs/real")
writer_fake_images = SummaryWriter(f"logs/fake")
logging_step = 0

# Training mode for models
generator.train()
discriminator.train()

# Training loop
start_time = time.time()
for epoch in range(total_epochs):
    for batch_index, (real_images, _) in enumerate(data_loader):
        real_images = real_images.to(device)

        # Training Discriminator
        for _ in range(critic_iterations):
            noise = torch.randn(
                (batch_size, latent_vector_dim, 1, 1)).to(device)
            fake_images = generator(noise)
            discriminator_real = discriminator(real_images).reshape(-1)
            discriminator_fake = discriminator(
                fake_images.detach()).reshape(-1)
            gradient_penalty = weight_penality(
                discriminator, real_images, fake_images, device=device)

            loss_discriminator = -(torch.mean(discriminator_real) - torch.mean(
                discriminator_fake)) + lambda_gradient_penalty * gradient_penalty
            discriminator.zero_grad()
            loss_discriminator.backward(retain_graph=True)
            optimizer_discriminator.step()

        # Training Generator
        """
         This line passes the fake images generated by the generator to the discriminator.
           The discriminator evaluates these images and outputs a score indicating how "real"
             each image looks.
        """
        generator_output = discriminator(fake_images).reshape(-1)
        loss_generator = -torch.mean(generator_output)
        generator.zero_grad()
        loss_generator.backward()
        optimizer_generator.step()

        # Logging and Visualization
        if batch_index % 100 == 0:
            print(f"Epoch [{epoch}/{total_epochs}] Batch {batch_index}/{len(data_loader)} \
                  Loss Discriminator: {loss_discriminator:.4f}, Loss Generator: {loss_generator:.4f}")

            with torch.no_grad():
                generated_fake = generator(fixed_noise_sample)
                grid_real_images = torchvision.utils.make_grid(
                    real_images[:32], normalize=True)
                grid_fake_images = torchvision.utils.make_grid(
                    generated_fake[:32], normalize=True)

                writer_real_images.add_image(
                    "Real Images", grid_real_images, global_step=logging_step)
                writer_fake_images.add_image(
                    "Fake Images", grid_fake_images, global_step=logging_step)

            logging_step += 1

end_time = time.time()
total_training_time = end_time - start_time
hours, minutes, seconds = total_training_time // 3600, (
    total_training_time % 3600) // 60, total_training_time % 60
print(f"Total training time: {int(hours)}h {int(minutes)}m {int(seconds)}s")
