import torch


def calculate_gradient_penalty(discriminator, real_samples, generated_samples, compute_device="cpu"):
    """
    Calculate the gradient penalty for a critic (discriminator) in a WGAN.
    This function helps to enforce the Lipschitz constraint and stabilize training.

    Parameters:
    - discriminator: The discriminator (or critic) model.
    - real_samples: Real images from the dataset.
    - generated_samples: Fake images generated by the generator.
    - compute_device: The device (CPU or GPU) to perform calculations on.

    Returns:
    - gradient_penalty: The calculated gradient penalty.
    """

    # Unpacking the shape of real images
    batch_size, channels, height, width = real_samples.shape

    # Random weight term for interpolation
    alpha = torch.rand((batch_size, 1, 1, 1)).repeat(
        1, channels, height, width).to(compute_device)

    # Interpolating between real and fake images
    interpolated_images = real_samples * \
        alpha + generated_samples * (1 - alpha)

    # Calculating the critic's scores on the interpolated images
    mixed_scores = discriminator(interpolated_images)

    # Calculating the gradients of the scores with respect to the images
    gradients = torch.autograd.grad(
        inputs=interpolated_images,
        outputs=mixed_scores,
        grad_outputs=torch.ones_like(mixed_scores),
        create_graph=True,
        retain_graph=True,
    )[0]

    # Reshaping the gradients to calculate the norm
    gradients = gradients.view(gradients.shape[0], -1)

    # Calculating the L2 norm of the gradients
    gradients_norm = gradients.norm(2, dim=1)

    # Calculating the gradient penalty
    gradient_penalty = torch.mean((gradients_norm - 1) ** 2)

    return gradient_penalty
